ali_source 'alibaba-specs' #集团内部仓库
ali_source 'alibaba-specs-mirror' #官方镜像仓库
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK',  '0.10.1.1'
    #pod 'WeexPlugin'
    pod 'WeexPlugin', :path=>'../'
end

target 'WeexPluginDemo' do
    common
end

